export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT';
export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS'
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";
export const GET_ASSIGNMENT = 'GET_ASSIGNMENT';